export const DOMAIN_ORDER = ["Economy", "Employment", "Education", "Ecology"] as const;
export const PRINCIPLE_ORDER = ["GMT", "ICV", "IIA", "ICI"] as const;

export type DomainLabel = (typeof DOMAIN_ORDER)[number];
export type PrincipleLabel = (typeof PRINCIPLE_ORDER)[number];

export const SITE_CONFIG = {
  repoOwner: "gyrogovernance",
  repoName: "moments",
  discussionCategorySlug: "moments",
  discussionCategoryName: "moments",
  repoId: "R_kgDOSKa-Mg",
  discussionCategoryId: "DIC_kwDOSKa-Ms4C7gT9",
  siteName: "Moments",
  siteDescription:
    "Share your vision of life beyond poverty, unemployment, misinformation, and ecological degradation.",
  siteUrl: "https://gyrogovernance.github.io/moments/",
  githubUrl: "https://github.com/gyrogovernance/moments",
  discussionsUrl: "https://github.com/gyrogovernance/moments/discussions",
  createMomentUrl: "https://github.com/gyrogovernance/moments/discussions/new?category=moments",
  primaryGradient: "from-classic-blue via-classic-purple to-classic-pink",
  domains: [
    {
      id: "Economy" as DomainLabel,
      slug: "economy",
      emoji: "💰",
      colorClass: "glass-card-amber",
      invitation: "Imagine abundance, not scarcity",
      prompt: "What would economic life look like if resources were truly available to everyone?",
      lens: "Share Moments about resources, distribution, material security, or practical economic coordination.",
      primaryPrinciple: "GMT" as PrincipleLabel,
    },
    {
      id: "Employment" as DomainLabel,
      slug: "employment",
      emoji: "🤝",
      colorClass: "glass-card-blue",
      invitation: "Imagine purpose, not precarity",
      prompt: "What would work look like if everyone could contribute without fighting for survival?",
      lens: "Share Moments about meaningful work, contribution pathways, or new forms of coordination.",
      primaryPrinciple: "IIA" as PrincipleLabel,
    },
    {
      id: "Education" as DomainLabel,
      slug: "education",
      emoji: "📚",
      colorClass: "glass-card-purple",
      invitation: "Imagine clarity, not confusion",
      prompt: "What would education look like if people could trust what they know?",
      lens: "Share Moments that teach, clarify, or help people see the difference between human and artificial sources.",
      primaryPrinciple: "ICV" as PrincipleLabel,
    },
    {
      id: "Ecology" as DomainLabel,
      slug: "ecology",
      emoji: "🌿",
      colorClass: "glass-card-emerald",
      invitation: "Imagine balance, not depletion",
      prompt: "What would balance look like if economy, employment, and education were aligned?",
      lens: "Share Moments about regeneration, stewardship, resilience, or whole-system balance.",
      primaryPrinciple: "ICI" as PrincipleLabel,
    },
  ],
  principles: [
    {
      id: "GMT" as PrincipleLabel,
      shortName: "Governance Management Traceability",
      fullName: "Governance Management Traceability",
      description: "Can you trace where a decision came from and who made it?",
      guidance: "Before you post: can someone trace the origin of the claim or decision you are sharing?",
      displacement: "Governance Traceability Displacement",
      displacementWarning: "Approaching Indirect Authority and Agency as Direct.",
    },
    {
      id: "ICV" as PrincipleLabel,
      shortName: "Information Curation Variety",
      fullName: "Information Curation Variety",
      description: "Are you seeing diverse sources, or just one type repeated?",
      guidance: "Before you post: does your Moment add a perspective that is missing, or repeat what is already there?",
      displacement: "Information Variety Displacement",
      displacementWarning: "Approaching Indirect Authority without Agency as Direct.",
    },
    {
      id: "IIA" as PrincipleLabel,
      shortName: "Inference Interaction Accountability",
      fullName: "Inference Interaction Accountability",
      description: "Is someone accountable for the conclusion, or did it appear from nowhere?",
      guidance: "Before you post: is it clear who stands behind the reasoning you are sharing?",
      displacement: "Inference Accountability Displacement",
      displacementWarning: "Approaching Indirect Agency without Authority as Direct.",
    },
    {
      id: "ICI" as PrincipleLabel,
      shortName: "Intelligence Cooperation Integrity",
      fullName: "Intelligence Cooperation Integrity",
      description: "Is the whole picture coherent, or are parts working against each other?",
      guidance: "Before you post: does your Moment strengthen the coherence of the domain, or fragment it?",
      displacement: "Intelligence Integrity Displacement",
      displacementWarning: "Approaching Direct Authority and Agency as Indirect.",
    },
  ],
} as const;
